logging:
  config: classpath:logback-spring.xml
  dir:  ${user.home}/${spring.application.name}/logs
  level:
    root: info
    org.springframework: info
    com.alibaba.chaosblade.platform: info

spring:
  application:
    name: chaos-platform
  datasource:
    url: jdbc:mysql://@mysql.url@/chaosblade?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: @mysql.username@
    password: @mysql.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

chaos:
  scene:
    import: true
    market: #https://chaosblade.oss-cn-hangzhou.aliyuncs.com/platform/market/chaostools/
    originals:
      litmus:
        - name: generic
          version: 1.13.0
          url: https://hub.litmuschaos.io/api/chaos/1.13.0?file=charts/generic/experiments.yaml
        #- name: kafka
        #  version: 1.13.0
        #  url: https://hub.litmuschaos.io/api/chaos/1.13.0?file=charts/kafka/experiments.yaml
  collector:
    enable: true
    type: kube_api
    period: 30
    prometheus:
      api:
  metric:
    aliyun:
  agent:
    port: 19527
    release: https://chaosblade.oss-cn-hangzhou.aliyuncs.com/platform/chaosagent
  ctl:
    agent: https://chaosblade.oss-cn-hangzhou.aliyuncs.com/platform/chaosagentctl.sh
    tools: https://chaosblade.oss-cn-hangzhou.aliyuncs.com/platform/chaostoolsctl.sh



